version: '3'

services:
  db:
    image: postgres
    volumes:
      - ./_db/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplepw
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
  backend:
    build: 
      context: .
      dockerfile: Dockerfile-django
    environment:
      - DJANGO_DB_HOST=db #services:db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplepw
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend/:/app/backend
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh db:5432 -t 10
        python manage.py runserver 0:8000
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile-react
    volumes:
      - ./frontend/:/app/frontend/
    ports:
      - "4000:3000"
    command: ["npm", "start"]
